-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와
-- 상품을 구매한 회원의 비율
--  (=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
--  을 년, 월 별로 출력하는 SQL문을 작성해주세요

-- WITH 없이 고정 값을 FROM SubQuery로 가져와서 풀기
SELECT YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / X.COUNT_USER, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
    INNER JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID,
    (
    SELECT COUNT(*) AS COUNT_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
    ) X
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY 1, 2
ORDER BY 1, 2;

-- WITH 로 임시 테이블 만들어두고 불러와서 풀기
WITH USER_COUNT AS
(
    SELECT COUNT(*) AS COUNT_ALL_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)


SELECT YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / UC.COUNT_ALL_USER, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
    INNER JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID,
    USER_COUNT UC
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY 1, 2
ORDER BY 1, 2;


-- WITH RECURSIVE
WITH RECURSIVE TMP_TBL AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM TMP_TBL WHERE H < 23
)