-- REST_INFO 테이블에서 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- RANK() OVER (PARTITION BY ~) 활용
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FOVARITES_RANK
      FROM REST_INFO) RANKS
WHERE RANKS.FOVARITES_RANK < 2
ORDER BY FOOD_TYPE DESC;