-- REST_INFO 테이블에서 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- RANK() OVER (PARTITION BY ~) 활용
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FOVARITES_RANK
      FROM REST_INFO) RANKS
WHERE RANKS.FOVARITES_RANK < 2
ORDER BY FOOD_TYPE DESC;

-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회하는 SQL문을 작성해주세요.
-- 이때 식품분류가 '과자', '국', '김치', '식용유'인 경우만 출력 -> CATEGORY WHERE
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (SELECT *,
             RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) RANKS
WHERE RANKS.PRICE_RANK < 2
ORDER BY MAX_PRICE DESC;