SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') SALES_DATE,
       A.PRODUCT_ID,
       A.USER_ID,
       A.SALES_AMOUNT
FROM (
         SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
         FROM ONLINE_SALE
         UNION ALL
         SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
         FROM OFFLINE_SALE
     ) A
WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID