-- LEFT: 왼쪽을 기준으로 추출
-- RIGHT: 오른쪽을 기준으로 추출
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(PRODUCT_ID)
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- SUBSTRING: start ~ end 추출
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_ID)
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- ORACLE, MYSQL 공통
-- SUBSTR: start ~ end 추출
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_ID)
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;